#!/usr/bin/env ruby

require 'benchmark'

system 'make > /dev/null'

20.times do
  Benchmark.benchmark do |x|
    x.report('BarrierArray:   ') { system 'java BarrierArray > /dev/null' }
    x.report('BarrierCounter: ') { system 'java BarrierCounter > /dev/null' }
  end
end

system 'make clean > /dev/null'
